{
  imports = [
    ../modules/bluetooth.nix
    ../modules/boot-message.nix
    ../modules/editor.nix
    ../modules/firmware.nix
    ../modules/flakes.nix
    ../modules/flipper-zero.nix
    ../modules/fonts.nix
    ../modules/grub.nix
    ../modules/home-related-hacks.nix
    ../modules/home.nix
    ../modules/networking.nix
    ../modules/nix.nix
    ../modules/graphics.nix
    ../modules/pipewire.nix
    ../modules/printing.nix
    ../modules/service-discovery.nix
    ../modules/shell.nix
    ../modules/steam.nix
    ../modules/sudo.nix
    ../modules/tmp.nix
    ../modules/user.nix
    ../modules/virtualbox.nix
    ../modules/zfs.nix
    ../modules/dconf.nix
    ../modules/catppuccin.nix
  ];
}
