{
  tui = [
    ./accounts.nix
    ./atuin.nix
    ./bottom.nix
    ./editorconfig.nix
    ./exa.nix
    ./gh.nix
    ./git.nix
    ./merely-enabled.nix
    ./neovim
    ./ssh.nix
    ./starship.nix
    ./tealdeer.nix
    ./tmux.nix
    ./udiskie.nix
    ./zsh
  ];
  gui = [
    ./alacritty.nix
    ./chromium.nix
    ./firefox.nix
    ./flameshot.nix
    ./fontconfig.nix
    ./gtk.nix
    ./neovide.nix
    ./obs-studio.nix
    ./sway-bars.nix
    ./sway-lock.nix
    ./sway-notifications.nix
    ./sway.nix
    ./vscodium.nix
    ./wlsunset.nix
    ./xdg-mime.nix
    ./xdg-user-dirs.nix
  ];
}
