{
  "jobs": {
    "check": {
      "runs-on": "ubuntu-latest",
      "steps": [
        {
          "uses": "actions/checkout@main"
        },
        {
          "uses": "wimpysworld/nothing-but-nix@main",
          "with": {
            "hatchet-protocol": "holster"
          }
        },
        {
          "uses": "DeterminateSystems/nix-installer-action@main"
        },
        {
          "uses": "DeterminateSystems/magic-nix-cache-action@main"
        },
        {
          "run": "nix --accept-flake-config flake check --print-build-logs --keep-going\n"
        }
      ]
    }
  },
  "name": "Check",
  "on": {
    "push": {},
    "workflow_call": {}
  }
}
